# Generated by Django 3.2.15 on 2023-05-24 08:38

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import apps.streams.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "title_and_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Add your title",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.TextBlock(
                                                help_text="Add additional text",
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("full_rich_text", apps.streams.blocks.RichTextBlock()),
                            (
                                "simple_rich_text",
                                apps.streams.blocks.SimpleRichtextBlock(),
                            ),
                            (
                                "cards",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Add your title",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=40,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(
                                                                max_length=200,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "button_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "button_url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="If the button page above is selected, that will be used first.",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                max_length=60, required=True
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.RichTextBlock(
                                                features=["bold", "italic"],
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "button_page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "button_url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                        (
                                            "button_text",
                                            wagtail.blocks.CharBlock(
                                                default="Learn More",
                                                max_length=40,
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flex Page",
                "verbose_name_plural": "Flex Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
